# Generated by Django 6.0.2 on 2026-03-01 12:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='booking',
            name='booking_boo_workspa_759090_idx',
        ),
        migrations.RemoveIndex(
            model_name='booking',
            name='booking_boo_custome_0332a3_idx',
        ),
        migrations.RemoveIndex(
            model_name='timeoff',
            name='booking_tim_workspa_baa80d_idx',
        ),
        migrations.RemoveField(
            model_name='availabilityrule',
            name='staff',
        ),
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('OWNER', 'Owner'), ('STAFF', 'Staff')], default='STAFF', max_length=10),
        ),
        migrations.AlterField(
            model_name='service',
            name='duration_min',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='currency',
            field=models.CharField(default='RON', help_text='Codul ISO al monedei (ex: RON, EUR, USD)', max_length=3),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['workspace', 'start_at'], name='booking_boo_workspa_be64b4_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['workspace', 'end_at'], name='booking_boo_workspa_a1b258_idx'),
        ),
        migrations.RemoveField(
            model_name='booking',
            name='cancelled_at',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='cancelled_by',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='price_amount',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='timeoff',
            name='staff',
        ),
    ]
