# Generated by Django 6.0.2 on 2026-08-13 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0002_review"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="booking",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="booking.booking",
            ),
        ),
    ]
