# Generated by Django 6.0.1 on 2026-08-23 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_review_booking'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='membership',
            name='unique_membership',
        ),
        migrations.DeleteModel(
            name='Membership',
        ),
    ]
